baseURL: "https://fatihemreozturk.netlify.app/"
languageCode: "en-us"
title: "feo"
theme: "hugo-profile"

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Fatih Emre Ozturk"
  description: feo's personal website
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/feopp.jpeg"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Fatih Emre Ozturk" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Fatih Emre Ozturk."
    subtitle: "I'm a Data Scientist"
    image: /images/feopp.jpeg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/ozturkfemre
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/ozturkfemre/
        - icon: fab fa-medium
          url: https://medium.com/@ozturkfemre


  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/feopp.jpeg"
    content: |-
     Hello there! I'm Fatih Emre Öztürk, a data wizard in the enchanting world of data science (or let's say, a bit of an R guru and a bit of a data bender). My title says Data Scientist, but I'm a rookie in terms of previous experience. However, my educational journey has been quite magical.
     
     After waltzing with philosophy at Bilkent University, I decided to embark on a thrilling adventure of pursuing a master's degree in Data Science at Dokuz Eylül University. I got lost in the enchanting realms of Python and R, and befriended magical tools like SQL, JavaScript, Matlab, and Excel. I also have a surprisingly good rapport with Bash (I'm quite spellbound by the power of commands). I possess magical skills like machine learning, data analysis, and crafting ML pipelines.
     
     During this enchanting journey, I've achieved some milestones. I completed my studies at Dokuz Eylül University with High Honor (no magic hat required!). Oh, and I have a passion for writing too—I've penned down two novels (guess I can weave data into characters' lives as well).
     
     Among my passions, you'll find me indulging in science fiction and fantasy books, movies, and series (I might be a bit of a geek). Additionally, I have a special interest in ethical issues related to AI—tackling the moral quandaries of artificial intelligence is right up my alley (I prefer embracing AI with a friendly approach instead of pushing its limits). If you ever get lost in the data realm, I can transform into a magical source of R!
     
     As for my professional goals, I aspire to develop algorithms that empower individuals and organizations to make better decisions, contributing to the advancement of AI and machine learning. I also aim to make our enchanting world more accessible by creating open-source resources alongside R and Python packages.
     
     Among my magical language skills, I possess English (at a professional working proficiency) and I can also converse in beginner-level French (Bonjour, ça va?). And of course, my native tongue is the enchanting Turkish!
     
     If you're up for a magical adventure in the world of data, feel free to reach out in a magically enchanting way! Remember, let the data be with you!"
    
     ------------------------------------------------------------------------
     
     ### EDUCATION
     - Master of Science in Data Science | Dokuz Eylul University, İzmir/Turkey	
     Feb 2022 — Aug 2023
     Department of Statistics | Advisor: Neslihan Demirel
     
     - Bachelor in Philosophy | Bilkent University, Ankara/Turkey
     Sep 2012  —  Jan 2019
     Department of Philosophy | Advisor: Bill Wringe
     
     ------------------------------------------------------------------------
     
     ### EXPERIENCE
     - Data Scientist | FinancialPredictionAI, Remote	
     April 2024 — Still
     
     - Subtitle Editor/Translator | Private Contractor,  Remote
     Sep 2021  —  Feb 2022
     
     ------------------------------------------------------------------------
      
      
      ### SKILLS
      
      - Programming: 
      Python, R, Sql, Bash, Git, Google Sheets, JavaScript
      - Documentation: 
      Microsoft PowerPoint, Microsoft Word, Markdown, Obsidian, Google Docs, Google Slides
      - Data Management: 
      MongoDB, DBBrowser
      - Statistical Analysis: 
      A/B Tests, RFM, KPIs, Hypothesis Testing, Anomaly Detection, Ethics and Privacy Awareness, Pandas(Python), Numpy(Python), Tidyverse(R), d3(JavaScript), Financial Analysis 
      - Machine Learning: 
      Regression, Classification, Clustering, Artificial Neural Networks, Tensorflow(Python), Sklearn(Python), PyTorch(Python)
      - Data Visualization/Storytelling: 
      Matplotlib(Python), Seaborn(Python), Plotnine(Python), Plotly(Python), Ggplot(R), Shiny(R) 
      - Soft Skills:
      Identifying & Solving Problems, Researching, Mentoring/Supervising, Report Writing, Project Management, Attention to Details, Workflow Development 
      
            
      ------------------------------------------------------------------------
      
      ### LANGUAGES
      
      - **Turkish:** *Native*
      - **English:** *IELTS 7.0*
      - **French:** *Beginner*
      
      
      ------------------------------------------------------------------------
      #### Conference Workshops
      
      - Lessons for Designing Scalable and Maintainable Shiny Apps \| useR! Jun 2022
      - Introduction to Git and Github \| useR! Jun 2022
      - Regression Modelling Strategies \| useR Jun 2022
      ------------------------------------------------------------------------
      
      ### ACADEMIC SERVICE
      
      Artificial Intelligence Symposium \| Mar 2015 \| Organizing Committee Member of the Bilkent University Philosophy Society
      DSM 5008 Unsupervised Statistical Learning Course \| May 24, 2023 \| Guest Lecturer | Dokuz Eylul University
      
      ------------------------------------------------------------------------
      
      ### CONFERENCES
      
      Oral talk titled "Comparison of the methods to determine the optimal number of clusters" \| Dec 2, 2022 \| Dokuz Eylul University International Graduate Research Symposium
      
      Participation \| Jun 20-23, 2022 \| Virtual \| useR! 2022
      
      ------------------------------------------------------------------------
      
      ### AWARDS
      - Full Scholarship 2012-2019 Bilkent University
      - Honor, 2014 Bilkent University
      - Honor, 2014 Bilkent University
      - High Honor, 2022 Dokuz Eylul University
      - High Honor, 2023 Dokuz Eylul University
      
      ------------------------------------------------------------------------
      
      ### PUBLICATIONS
      Öztürk, F. E. and Demirel, N. (2023). Comparison of the methods to determine optimal number of clusters. Veri Bilimi Derg 6 (1) , 34-45
      
      
      ------------------------------------------------------------------------

      ### Technical Training:
      
      
      #### University courses
      - Calculus I & Calculus II \| Sep 2013 & Jan 2014
      - Introduction to Computing and Programming \| Jan 2014 
      - Introduction to Probability and Statistics \| Jun 2014
      - Python for Data Science \| Jan 2022
      - Exploratory Data Analysis and Data Visualization \| Jan 2022
      - Unsupervised Statistical Learning \| Jan 2022 
      - Supervised Statistical Learning \| Sep 2022
      - R for Statistical Computing and Programming \| Sep 2022
      - Probability and Statistics for Data Science \| Sep 2022
      
      
      #### Online courses
      - Python for Data Science and Artificial Intelligence \| Udemy\| Nov 2021
      - Python for Data Science and Machine Learning Bootcamp \| Udemy \| Dec 2021
      - Data Management with SQL for Social Scientists \| Data Carpentry \| Nov 2021
      - Introduction to Geospatial Concepts \| Data Carpentry \| Jan 2022
      - Introduction to R for Geospatial Data \| Data Carpentry \| Jan 2022
      - Programming with Python \| Software Carpentry \| Nov 2021
      - Programming with R \| Software Carpentry \| Nov 2021
      - Version Control with Git \| Software Carpentry \| Dec 2021
      ------------------------------------------------------------------------
      
      ### INTERESTS
      - Chess 
      - Reading and Watching Sci-fi 
      - Fitness
      - Writing
      - Collecting Playing Cards
      - Game Development
      


        
  education:
    enable: false
    # title: "Custom Name"
    index: false
    items:
      - title: "Master of Science in Data Science"
        school:
          name: "Dokuz Eylul University, Izmir"
          url: ""
        date: "2022 - 2023"
        
      
      - title: "Bachelor in Philosophy"
        school:
          name: "Bilkent University, Ankara"
          url: ""
        date: "2012 - 2019"
        content: 
  # Experience
  experience:
    enable: false
    # title: "Custom Name"
    index: false
    items:
      - title: "Data Scientist"
        school:
          name: "Financial Preediction AI"
          url: ""
        date: "April 2024 - Still"
        
      
      - title: "Subtitle Translator/Editor"
        school:
          name: "Private Contractor"
          url: ""
        date: "Sep 2021 - Feb 2022"
        content: 


  # Achievements
  training:
    enable: false
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Examining Prefrontal Oxygenation Parameter in Migraine Classification
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: My tasks included data cleaning, feature extraction, feature reduction, and building machine learning pipelines. We carried out this study in coordination with the Department of Statistics and the Department of Biophysics at Dokuz Eylul University. 
        featured:
          name: 
          link: 


      - title: Comparison of the methods to determine optimal number of clusters
        content: In this project, I compared the methods to determine optimal number of clusters(Average Silhouette, Calinski-Harabasz, Davies-Bouldin, and Dunn Index) on nine different data sets. I tested which method works better in which cases and for which types of data sets they fail. This study was published in 'Veri Bilimi', a national peer-reviewed journal.
        links:
          - icon: 
            url: https://github.com/ozturkfemre/optimal_k

      - title: Analyse Your Spotify Listening
        content: Spotify offers its users analyses according to their listening habits every year. However, each user can access their own data at any time. I made a web application for users by combining these two features. With this app users can analyse their Spotify data with simple plots. All they have to do is request their data from Spotify!
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: ozturkfemre@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
    


  footer:
    socialNetworks:
      github: https://github.com/ozturkfemre
      linkedin: https://www.linkedin.com/in/ozturkfemre/
      twitter: https://twitter.com/ozturkfemre
      instagram: https://instagram.com/ozturkfemre


  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
