<!DOCTYPE html>
<html lang='en'><head>
  <title>Infinite Monkey - feo</title>
  <link rel='canonical' href='https://example.com/post/infmonkey/' />
  <meta charset='utf-8'>
  <meta name='viewport' content='width=device-width, initial-scale=1' />
  <meta name='description' content='Infinite Monkey Theorem in R' />
  <meta name='theme-color' content='#FD3519' />
  

  <meta name="generator" content="Hugo 0.111.3">

  





<link rel="stylesheet" href="https://example.com/sass/style.min.eabe1aa4bd266a15f7b39b122bd6a5cc75cb067e5373631ac21d7815d6240d6f.css" integrity="sha256-6r4apL0mahX3s5sSK9alzHXLBn5Tc2Mawh14FdYkDW8=" media="screen">
<link rel="stylesheet" href="https://example.com/syntax.min.css" integrity="" media="screen">

  <meta property="og:title" content="Infinite Monkey" />
<meta property="og:description" content="Infinite Monkey Theorem in R" />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://example.com/post/infmonkey/" /><meta property="article:section" content="post" />
<meta property="article:published_time" content="2023-03-02T23:06:29+02:00" />
<meta property="article:modified_time" content="2023-03-02T23:06:29+02:00" />

  <meta itemprop="name" content="Infinite Monkey">
<meta itemprop="description" content="Infinite Monkey Theorem in R"><meta itemprop="datePublished" content="2023-03-02T23:06:29+02:00" />
<meta itemprop="dateModified" content="2023-03-02T23:06:29+02:00" />
<meta itemprop="wordCount" content="1800">
<meta itemprop="keywords" content="" />
</head>
<body>

  <header style="background-image:linear-gradient(
      rgba(0,0,0,0.4),rgba(0,0,0,0.4)
    ),url(&#39;https://example.com/images/background.jpg&#39;)">
  <div class="intro">
    <div class="logo-container">
      <a href="/">
        <img src='https://example.com/images/feopp.jpeg' alt="Profile Technical Training" class="rounded-logo">
      </a>
    </div>
    <h2>Fatih Emre Ozturk</h2>
    <h3>Data Scientist</h3>
    <div class="menu">
      

        <p>
            <a href="/about/">
                About
            </a>
        </p>

        <p>
            <a href="/portfolio/">
                Technical Training
            </a>
        </p>

        <p>
            <a href="/post/">
                Post
            </a>
        </p>

      
        
        <p>
            <a href="mailto:ozturkfemre@gmail.com" target="_blank" rel="external">
                email me
            </a>
        </p>
      
    </div>
  </div>

  <div class="socials">
      
  
    <a href="https://github.com/ozturkfemre" class="social-link" target="_blank" rel="noopener" ><div class="icon">
  <svg width="35px" height="35px" viewBox="0 0 115 115" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img">
  
  <path d="M102.679 0H12.32C5.52 0 0 5.519 0 12.321v90.358C0 109.48 5.519 115 12.321 115h90.358c6.802 0 12.321-5.519 12.321-12.321V12.32C115 5.52 109.481 0 102.679 0zM71.182 98.494c-2.156.385-2.952-.95-2.952-2.053 0-1.386.051-8.471.051-14.195 0-4.005-1.335-6.546-2.9-7.881C74.878 73.313 84.89 72.003 84.89 55.6c0-4.671-1.669-7.007-4.39-10.01.436-1.105 1.9-5.648-.436-11.552-3.568-1.104-11.731 4.595-11.731 4.595-3.389-.95-7.06-1.438-10.679-1.438-3.62 0-7.29.488-10.679 1.438 0 0-8.163-5.699-11.73-4.595-2.337 5.878-.899 10.422-.437 11.551-2.72 3.004-4.004 5.34-4.004 10.011 0 16.326 9.574 17.712 19.072 18.765-1.232 1.104-2.336 3.003-2.72 5.724-2.44 1.104-8.677 3.004-12.4-3.568-2.335-4.056-6.545-4.39-6.545-4.39-4.159-.05-.282 2.619-.282 2.619 2.772 1.283 4.723 6.212 4.723 6.212 2.49 7.624 14.4 5.057 14.4 5.057 0 3.568.052 9.37.052 10.422 0 1.104-.77 2.438-2.952 2.053C27.21 92.821 15.35 76.701 15.35 57.86c0-23.564 18.02-41.456 41.585-41.456s42.663 17.892 42.663 41.456c.026 18.842-11.474 34.988-28.416 40.635zM46 82.81c-.488.103-.95-.102-1.001-.436-.051-.385.282-.719.77-.822.488-.05.95.154 1.001.488.077.334-.257.668-.77.77zm-2.439-.23c0 .333-.385.615-.898.615-.565.052-.95-.23-.95-.616 0-.333.385-.616.899-.616.487-.051.95.231.95.616zm-3.516-.283c-.103.334-.616.488-1.053.334-.488-.103-.821-.488-.719-.822.103-.334.617-.488 1.053-.385.513.154.847.54.719.873zm-3.158-1.386c-.23.282-.718.23-1.104-.154-.385-.334-.487-.822-.23-1.053.23-.282.718-.23 1.103.154.334.334.462.847.231 1.053zm-2.336-2.336c-.23.154-.667 0-.95-.385-.282-.385-.282-.822 0-1.001.283-.231.72-.052.95.333.283.385.283.847 0 1.053zm-1.668-2.49c-.231.23-.616.103-.899-.154-.282-.334-.333-.719-.102-.899.23-.23.616-.102.898.154.282.334.334.72.103.899zm-1.72-1.9c-.103.231-.436.283-.719.103-.334-.154-.488-.436-.385-.667.103-.154.385-.231.719-.103.334.18.488.462.385.667z"/>
  
  </svg>
</div>
</a>
  

  
    <a href="https://www.linkedin.com/in/ozturkfemre" class="social-link" target="_blank" rel="noopener" ><div class="icon">
  <svg width="35px" height="35px" viewBox="0 0 115 115" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img">
  
  <path d="M106.786 0H8.189C3.67 0 0 3.722 0 8.291v98.418C0 111.278 3.67 115 8.189 115h98.597c4.518 0 8.214-3.722 8.214-8.291V8.29C115 3.722 111.304 0 106.786 0zm-72.03 98.571H17.713V43.69h17.07V98.57h-.025zm-8.522-62.377c-5.467 0-9.882-4.44-9.882-9.883 0-5.442 4.415-9.882 9.882-9.882 5.442 0 9.883 4.44 9.883 9.882a9.87 9.87 0 0 1-9.883 9.883zm72.414 62.377H81.604V71.875c0-6.366-.129-14.555-8.856-14.555-8.882 0-10.242 6.931-10.242 14.093V98.57H45.46V43.69h16.352v7.495h.23c2.285-4.312 7.855-8.856 16.147-8.856 17.25 0 20.458 11.372 20.458 26.158V98.57z"/>
  
  </svg>
</div>
</a>
  

  
    <a href="https://medium.com/@ozturkfemre" class="social-link" target="_blank" rel="noopener" ><div class="icon">
  <svg width="35px" height="35px" viewBox="0 0 115 115" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img">
  
  <path d="M0 0v115h115V0H0zm95.542 27.235l-6.16 5.905a1.81 1.81 0 0 0-.693 1.72v43.458c-.103.667.154 1.335.693 1.72l6.032 5.904v1.31h-30.29v-1.259l6.238-6.058c.616-.616.616-.795.616-1.72V43.074L54.625 87.123h-2.336l-20.202-44.05v29.52c-.18 1.233.257 2.49 1.13 3.39l8.111 9.83v1.31H18.277v-1.31l8.111-9.83a3.93 3.93 0 0 0 1.053-3.39v-34.14a2.93 2.93 0 0 0-.976-2.516l-7.213-8.702v-1.309h22.41l17.301 37.991 15.222-37.965h21.357v1.283z"/>
  
  </svg>
</div>
</a>
  

  </div>
</header>

<div class="mobile-header">
  <p> feo </p>
  <div class="hamburger">
    <div class="bar"></div>
    <div class="bar"></div>
    <div class="bar"></div>
  </div>
</div>

<div class="overlay-menu">
  <header>
    <div class="intro">
      <div class="logo-container">
        <a href="/">
          <img src='https://example.com/images/feopp.jpeg' alt="Profile Technical Training" class="rounded-logo">
        </a>
      </div>
      <h2>Fatih Emre Ozturk</h2>
      <h3>Data Scientist</h3>
      <div class="menu">
        

        <p>
            <a href="/about/">
                About
            </a>
        </p>

        <p>
            <a href="/portfolio/">
                Technical Training
            </a>
        </p>

        <p>
            <a href="/post/">
                Post
            </a>
        </p>

        
          
          <p>
              <a href="mailto:ozturkfemre@gmail.com" target="_blank" rel="external">
                  email me
              </a>
          </p>
        
      </div>
    </div>

    <div class="socials">
        
  
    <a href="https://github.com/ozturkfemre" class="social-link" target="_blank" rel="noopener" ><div class="icon">
  <svg width="35px" height="35px" viewBox="0 0 115 115" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img">
  
  <path d="M102.679 0H12.32C5.52 0 0 5.519 0 12.321v90.358C0 109.48 5.519 115 12.321 115h90.358c6.802 0 12.321-5.519 12.321-12.321V12.32C115 5.52 109.481 0 102.679 0zM71.182 98.494c-2.156.385-2.952-.95-2.952-2.053 0-1.386.051-8.471.051-14.195 0-4.005-1.335-6.546-2.9-7.881C74.878 73.313 84.89 72.003 84.89 55.6c0-4.671-1.669-7.007-4.39-10.01.436-1.105 1.9-5.648-.436-11.552-3.568-1.104-11.731 4.595-11.731 4.595-3.389-.95-7.06-1.438-10.679-1.438-3.62 0-7.29.488-10.679 1.438 0 0-8.163-5.699-11.73-4.595-2.337 5.878-.899 10.422-.437 11.551-2.72 3.004-4.004 5.34-4.004 10.011 0 16.326 9.574 17.712 19.072 18.765-1.232 1.104-2.336 3.003-2.72 5.724-2.44 1.104-8.677 3.004-12.4-3.568-2.335-4.056-6.545-4.39-6.545-4.39-4.159-.05-.282 2.619-.282 2.619 2.772 1.283 4.723 6.212 4.723 6.212 2.49 7.624 14.4 5.057 14.4 5.057 0 3.568.052 9.37.052 10.422 0 1.104-.77 2.438-2.952 2.053C27.21 92.821 15.35 76.701 15.35 57.86c0-23.564 18.02-41.456 41.585-41.456s42.663 17.892 42.663 41.456c.026 18.842-11.474 34.988-28.416 40.635zM46 82.81c-.488.103-.95-.102-1.001-.436-.051-.385.282-.719.77-.822.488-.05.95.154 1.001.488.077.334-.257.668-.77.77zm-2.439-.23c0 .333-.385.615-.898.615-.565.052-.95-.23-.95-.616 0-.333.385-.616.899-.616.487-.051.95.231.95.616zm-3.516-.283c-.103.334-.616.488-1.053.334-.488-.103-.821-.488-.719-.822.103-.334.617-.488 1.053-.385.513.154.847.54.719.873zm-3.158-1.386c-.23.282-.718.23-1.104-.154-.385-.334-.487-.822-.23-1.053.23-.282.718-.23 1.103.154.334.334.462.847.231 1.053zm-2.336-2.336c-.23.154-.667 0-.95-.385-.282-.385-.282-.822 0-1.001.283-.231.72-.052.95.333.283.385.283.847 0 1.053zm-1.668-2.49c-.231.23-.616.103-.899-.154-.282-.334-.333-.719-.102-.899.23-.23.616-.102.898.154.282.334.334.72.103.899zm-1.72-1.9c-.103.231-.436.283-.719.103-.334-.154-.488-.436-.385-.667.103-.154.385-.231.719-.103.334.18.488.462.385.667z"/>
  
  </svg>
</div>
</a>
  

  
    <a href="https://www.linkedin.com/in/ozturkfemre" class="social-link" target="_blank" rel="noopener" ><div class="icon">
  <svg width="35px" height="35px" viewBox="0 0 115 115" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img">
  
  <path d="M106.786 0H8.189C3.67 0 0 3.722 0 8.291v98.418C0 111.278 3.67 115 8.189 115h98.597c4.518 0 8.214-3.722 8.214-8.291V8.29C115 3.722 111.304 0 106.786 0zm-72.03 98.571H17.713V43.69h17.07V98.57h-.025zm-8.522-62.377c-5.467 0-9.882-4.44-9.882-9.883 0-5.442 4.415-9.882 9.882-9.882 5.442 0 9.883 4.44 9.883 9.882a9.87 9.87 0 0 1-9.883 9.883zm72.414 62.377H81.604V71.875c0-6.366-.129-14.555-8.856-14.555-8.882 0-10.242 6.931-10.242 14.093V98.57H45.46V43.69h16.352v7.495h.23c2.285-4.312 7.855-8.856 16.147-8.856 17.25 0 20.458 11.372 20.458 26.158V98.57z"/>
  
  </svg>
</div>
</a>
  

  
    <a href="https://medium.com/@ozturkfemre" class="social-link" target="_blank" rel="noopener" ><div class="icon">
  <svg width="35px" height="35px" viewBox="0 0 115 115" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img">
  
  <path d="M0 0v115h115V0H0zm95.542 27.235l-6.16 5.905a1.81 1.81 0 0 0-.693 1.72v43.458c-.103.667.154 1.335.693 1.72l6.032 5.904v1.31h-30.29v-1.259l6.238-6.058c.616-.616.616-.795.616-1.72V43.074L54.625 87.123h-2.336l-20.202-44.05v29.52c-.18 1.233.257 2.49 1.13 3.39l8.111 9.83v1.31H18.277v-1.31l8.111-9.83a3.93 3.93 0 0 0 1.053-3.39v-34.14a2.93 2.93 0 0 0-.976-2.516l-7.213-8.702v-1.309h22.41l17.301 37.991 15.222-37.965h21.357v1.283z"/>
  
  </svg>
</div>
</a>
  

    </div>
  </header>
</div>

  <div class="content-wrapper">
    
      <div class="breadcrumb">
  





<span >
  <a href="https://example.com/"></a>
   / 
</span>


<span >
  <a href="https://example.com/post/">POST</a>
   / 
</span>


<span  class="active">
  <a href="https://example.com/post/infmonkey/">Infinite Monkey</a>
  
</span>

</div>

    
    <main id="content" class="post">

<h1>Infinite Monkey</h1>
<div class="reading-time">
  <div class="icon">
  <svg width="18px" height="18px" viewBox="0 0 115 115" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img">
  
  <path d="M57.5 11C29.05 11 6 34.05 6 62.5S29.05 114 57.5 114 109 90.95 109 62.5 85.95 11 57.5 11zm0 93.032c-22.947 0-41.532-18.585-41.532-41.532 0-22.947 18.585-41.532 41.532-41.532 22.947 0 41.532 18.585 41.532 41.532 0 22.947-18.585 41.532-41.532 41.532zm12.833-21.68L52.703 69.54a2.508 2.508 0 0 1-1.018-2.015V33.427a2.5 2.5 0 0 1 2.492-2.492h6.646a2.5 2.5 0 0 1 2.492 2.492v29.426l13.871 10.092c1.122.81 1.35 2.368.54 3.49l-3.904 5.377a2.51 2.51 0 0 1-3.489.54z"/>
  
  </svg>
</div>

  <span>9 minutes</span>
</div>

<div class="published-date">
  <div class="icon">
  <svg width="18px" height="18px" viewBox="0 0 115 115" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img">
  
  <path d="M77.577 51.23a1.807 1.807 0 0 0-2.2.342l-27.562 27.79a1.807 1.807 0 0 1-2.2.342l-14.008-9.702a1.807 1.807 0 0 0-2.2.342l-1.952 1.968c-.287.22-.456.568-.455.936.001.37.172.716.46.934L45.637 86.77a1.807 1.807 0 0 0 2.2-.342l31.709-31.97c.287-.22.456-.567.455-.936a1.175 1.175 0 0 0-.46-.933l-1.963-1.36z"/><path d="M97.304 20H80.512c-.041.34-.063.683-.064 1.026a5.986 5.986 0 0 0 1.256 4.1c.054.003.103.02.157.025a4.881 4.881 0 0 1 1.865-.025c3.05.562 4.984 3.907 4.32 7.47-.666 3.563-3.678 5.996-6.728 5.433a4.932 4.932 0 0 1-2.437-1.258c-6.018-1.378-10.445-7.795-10.445-15.745 0-.347.023-.685.04-1.026H34.579c-.041.34-.063.683-.064 1.026a5.986 5.986 0 0 0 1.256 4.1c.054.003.103.02.157.025a4.881 4.881 0 0 1 1.865-.025c3.05.562 4.984 3.907 4.32 7.47-.666 3.563-3.678 5.996-6.728 5.433a4.932 4.932 0 0 1-2.437-1.258c-6.018-1.378-10.445-7.795-10.445-15.745 0-.22.019-.434.025-.652a9.788 9.788 0 0 0-5.697 4.471 9.683 9.683 0 0 0-2.65 4.764L1.158 92.871c-.965 4.689 2.6 8.503 7.948 8.503h6.334v2.673c-.077 5.41 4.263 9.861 9.705 9.953h72.16c5.438-.095 9.774-4.546 9.694-9.953V29.953c.08-5.407-4.256-9.858-9.695-9.953zM10.078 96.653c-2.378 0-3.964-1.697-3.535-3.782L16.637 43.84h80.787L87.331 92.871a5.254 5.254 0 0 1-5.091 3.782H10.078zm91.535 7.394c.036 2.403-1.891 4.382-4.308 4.424h-72.16c-2.42-.04-4.352-2.018-4.32-4.424v-2.673h60.443c5.348 0 10.484-3.814 11.449-8.503l8.897-43.215v54.391z"/><path d="M34.814 33c1.243 0 2.251-1.057 2.251-2.36 0-1.305-1.008-2.362-2.25-2.362-2.04 0-4.313-3.194-4.313-7.778s2.272-7.778 4.312-7.778c1.227 0 2.536 1.163 3.386 3.084H43C41.716 11.19 38.578 8 34.814 8 29.871 8 26 13.49 26 20.5c0 7.009 3.871 12.5 8.814 12.5z"/>
  
  </svg>
</div>

  <span>March 2, 2023</span>
</div>

<hr>
<p>Living is the art of dealing with as many problems as there are solutions. For this reason, as long as we are alive, we constantly have to struggle with a number of problems.</p>
<p>There will always be problems, waiting to be solved. All we need to do is to try over and over again to overcome them. Just like Albert Einstein states:</p>
<blockquote>
<p>&quot;It's not that I'm so smart, it's just that I stay with problems longer.&quot;</p>
</blockquote>
<p>In this article, I'm going to repeat the Infinite Monkey theorem using the R programming language, which I think can make you feel better when you think you are in a difficult situation.</p>
<p><img src="https://cdn-images-1.medium.com/max/800/1*dxAcWmaMzQjykN9nVN5aCQ.jpeg" alt=""></p>
<p>The infinite monkey theorem is a hypothesis that states that an infinite number of monkeys, given an infinite amount of time and typewriters, would eventually produce the complete works of William Shakespeare or any other written text[1]. The idea behind the theorem is that given enough time and randomness, even highly improbable events can occur. The earliest known reference to the idea of monkeys typing at random comes from a 1913 essay by French mathematician Émile Borel, who used the concept to illustrate the concept of probability.</p>
<p>The statistical proof of the theorem can be explained in a basic form as if two events are statistically independent (the events do not affect each other's outcome), the probability of these two events occurring together is equal to the product of the probabilities of these events occurring separately.</p>
<p>In fact, it can also be said that this theorem also points us to the Gambler's Fallacy[2], a logical fallacy that many people fall victim to. To illustrate this fallacy, consider the classical coin toss experiment. Most people assume that because a coin has come up heads several times in a row, it's more likely to come up tails in the next flip. However, it is absolutely impossible to know this for sure. After all, the probability for each independent flip is always 50%. Of course, this only applies if the coin is not cheated.</p>
<p>Now, I am going to create a monkey to implement this theorem in R. This monkey is of course a function. Then I will try to randomly print some text to this monkey.</p>
<p>I think it is a good coding exercise to put some theorems, thought experiments, ideas into code. <em>Thinking like a machine(algorithmic thinking)</em> can be the most important component to turn the ideas in your mind into code. So, if you are faced with a task that you have never encountered before and you don't know what to do, instead of struggling with writing the code, you can create a road map for yourself. This road map will actually &quot;code&quot; your coding skills. In this project, I will also show how I cope with this situation.</p>
<p>What do I need to do to code the infinite monkey theory?</p>
<p>Of course, I need the monkey! Lets create our monkey that randomly hits keys on a typewriter.</p>
<pre><code>monkey_the_author &lt;- function(passage) {
  chars &lt;- c(letters, &quot; &quot;)
  paste0(sample(chars, length(passage[1]), replace = TRUE), collapse = &quot;&quot;)
</code></pre>
<p>After I have monkey, I need to do the experiment. Let's start with a simple single word, <code>monkey</code>.</p>
<p>To wrote this code, basically, I can say that I think in this way:</p>
<p><em>I have a monkey that hits random keys. I'm going to ask this monkey to type a certain text, so I know the length of this text, I know the content of this text. When the monkey presses random keys, I have to make sure that the key it presses is the same as my target passage. And I have to keep doing this until the condition I want is met. So instead of for, I need to use a repeat loop. And the end of this loop is when the monkey reaches the final text.</em></p>
<p>To make it easy to understand, I wrote explanation about what each line does in code chunk!</p>
<pre><code>passage1 &lt;- (&quot;monkey&quot;)

count &lt;- 0 # I want to know how many hits the monkey needed to write the passage.
set.seed(123)
repeat { # I will use repeat loop because the loop has to continue until the condition I want is met.
  count &lt;- count + 1
  test_passage &lt;- rep(&quot;&quot;, length(passage1)) # vector to store the generated text.
  for (i in 1:length(passage1)) { # iterate through each line 
    for (j in 1:nchar(passage1[[i]])) { # iterate through each character
      test_char &lt;- monkey_the_author(passage1) # monkey hits
      # for each character, the loop generates random strings until a character that matches the corresponding character in the target text is found.
      while (test_char != substr(passage1[[i]], j, j)) { # it uses the substr function to extract the character from the target text and compare it to the generated character.
        test_char &lt;- monkey_the_author(passage1) # if the generated character does not match the target character, the loop generates another random string and continues until a match is found
        count &lt;- count + 1 # to keep track of the number of attempts required
      }
      test_passage[i] &lt;- paste0(test_passage[i], test_char) # Once a match is found, the loop concatenates the matched character to the current line
    }
  }
  if (identical(test_passage, passage1)) { # If the entire test_passage vector matches the passage vector
    break # the loop breaks
  }
}
</code></pre>
<p>Experiment is over. Now, let us check whether the entire test_passage matches the original passage.</p>
<pre><code>test_passage

## [1] &quot;monkey&quot;
</code></pre>
<p>Now, let us see how many attempts required to generate the target passage. test_passage</p>
<pre><code>cat(&quot;It took&quot;, count, &quot;attempts to generate the target passage.&quot;)

## It took 148 attempts to generate the target passage.
</code></pre>
<p>Even though we succeeded with a low number of attempts, 148, what was the probability that a monkey pressing random keys would type this word correctly?</p>
<p>The word &quot;monkey&quot; has 6 letters. At first, we need to determine the total number of possible ways to draw 6 letters from the 26 letters of the alphabet with replacement. Since we are drawing with replacement, each letter can be drawn more than once, so the number of ways to draw 6 letters from 26 with replacement is:</p>
<p>26⁶ = 26 x 26 x 26 x 26 x 26 x 26 = 308,915,776</p>
<p>This means there are 308,915,776 possible 6-letter combinations that can be drawn with replacement from the alphabet.</p>
<p>To calculate the probability of spelling &quot;monkey&quot;, we need to determine how many of these 6-letter combinations contain the letters &quot;m&quot;, &quot;o&quot;, &quot;n&quot;, &quot;k&quot;, &quot;e&quot;, and &quot;y&quot; in the correct order. Since each letter can be drawn with replacement, the probability of drawing any particular letter is 1/26.</p>
<p>To calculate the probability of drawing all 6 letters in the correct order, we simply multiply the probability of drawing each letter:</p>
<p>(1/26) x (1/26) x (1/26) x (1/26) x (1/26) x (1/26) = 1/308,915,776</p>
<p>So the probability of spelling &quot;monkey&quot; by randomly drawing 6 letters from the alphabet with replacement is approximately 1 in 308,915,776 or 0.000000324%. This is amazing!</p>
<hr>
<p>Now, let me repeat the experiment with a more complicated passage which is &quot;monkey wrote this passage&quot;. I run the code again by repeating the steps I did for the word &quot;monkey&quot;.</p>
<pre><code>passage2 &lt;- (&quot;monkey wrote this passage&quot;)

# again, the same processes

count2 &lt;- 0
set.seed(122)
repeat {
  count2 &lt;- count2 + 1
  test_passage2 &lt;- rep(&quot;&quot;, length(passage2))
  for (i in 1:length(passage2)) {
    for (j in 1:nchar(passage2[[i]])) {
      test_char2 &lt;- monkey_the_author(passage2)
      while (test_char2 != substr(passage2[[i]], j, j)) {
        test_char2 &lt;- monkey_the_author(passage2)
        count2 &lt;- count2 + 1
      }
      test_passage2[i] &lt;- paste0(test_passage2[i], test_char2)
    }
  }
  if (identical(test_passage2, passage2)) {
    break
  }
}
</code></pre>
<p>Let us check whether the entire test_passage matches the original passage.</p>
<pre><code>test_passage2

## [1] &quot;monkey wrote this passage&quot;
</code></pre>
<p>Let us see how many attempts required to generate the target passage</p>
<pre><code>cat(&quot;It took&quot;, count2, &quot;attempts to generate the target passage.&quot;)

## It took 744 attempts to generate the target passage.
</code></pre>
<p>Again, even though we succeeded with a relatively low number of attempts, 744, what was the probability that a monkey pressing random keys would type this word correctly?</p>
<p>The sentence &quot;monkey wrote this passage&quot; has 23 letters. Thus, firstly, we first need to determine the total number of possible ways to draw 23 letters from the 26 letters of the alphabet with replacement. Since we are drawing with replacement, each letter can be drawn more than once, so the number of ways to draw 23 letters from 26 with replacement is:</p>
<p>26²³ = 351,843,720,888,320,000,000,000,000</p>
<p>This means there are 351,843,720,888,320,000,000,000,000 possible 23-letter combinations that can be drawn with replacement from the alphabet.</p>
<p>To calculate the probability of spelling &quot;monkey wrote this passage&quot;, we need to determine how many of these 23-letter combinations contain the letters in the correct order. Since each letter can be drawn with replacement, the probability of drawing any particular letter is 1/26.</p>
<p>To calculate the probability of drawing all 23 letters in the correct order, we simply multiply the probability of drawing each letter:</p>
<p>(1/26)²³ = 1/817,0728068870529046&hellip; × 10²³</p>
<p>So the probability of spelling &quot;monkey wrote this passage&quot; by randomly drawing 23 letters from the alphabet with replacement(hang on to your hat!) is approximately 1 in 8.170728068870529046&hellip; × 10²³ or 0.0000000000000000000000000000000000000000865% !!!!!</p>
<p>Not surprisingly, As the number of words in the passage that the monkeys are asked to write increases, the number of iterations in the loop, i.e. the number of attemps required, will also increase. This inevitable relationship is actually the basis of the theorem. Aside from the astonishment of realizing such low probabilities, however, it is also possible to interpret this theorem from another perspective. For example, it took 148 attempts for monkeys to type the word <code>monkey</code> by pressing random keys. What would happen if I used a for loop instead of repeat and iterated the loop 147 times?</p>
<p>Yes, sometimes a certain number of iterations will be enough to achieve the goal. But the thing to never forget is the real key to success: keep going until the condition is met! <code>Repeat</code>doing what you need to do to get what you want, until you get what you want! If you are struggling to achieve something you want to achieve and you can't get it even after countless attempts, you either don't have enough time or you don't have enough resources. Keep trying, get the resources you need (try a <code>repeat</code>loop instead of a <code>for</code>loop), and eventually you will succeed!</p>
<blockquote>
<p>If you have enough time and resources, you can perform an event with a probability of 0.0000000000000000000000000000000000000000000000000000000000000000865%.</p>
</blockquote>
<p>Let's end this project with the output of the code whose input I have hidden. Let's see what the monkey wrote for us[3] this time.</p>
<pre><code>## i am the master of my fate 
##  i am the captain of my soul
</code></pre>
<hr>
<p><strong>Readings</strong></p>
<p>[1] Crowley, John. &quot;The Million Monkeys of M. Borel.&quot; Conjunctions 67 (2016): 57&ndash;60.</p>
<p>[2] <a href="https://yourlogicalfallacyis.com/the-gamblers-fallacy">https://yourlogicalfallacyis.com/the-gamblers-fallacy</a></p>
<p>[3] <a href="https://www.poetryfoundation.org/poems/51642/invictus">https://www.poetryfoundation.org/poems/51642/invictus</a></p>


    </main>
  </div>
  <footer>
    <div class="footer-wrapper">
      <p>Made with ❤️ &mdash; Powered by <a href="https://gohugo.io/" target="_blank" rel="external">Hugo</a> and the <a href="https://github.com/bjacquemet/personal-web" target='_blank' rel="external">Personal Web</a> theme. Icons come from the great <a href="https://fontawesome.com/license" target="_blank" rel="external">Font Awesome</a> library</p>
      <p>© Fatih Emre Ozturk</p>
    </div>
  </footer>
  <link href="https://fonts.googleapis.com/css?family=Montserrat:500,600|Raleway:400,400i,600" rel="stylesheet">
  
  <script type="text/javascript">
    document.querySelector('.mobile-header').addEventListener('click', function () {
      var om = document.querySelector(".overlay-menu");
      if (document.querySelector('.hamburger').classList.contains("cross")) {
        document.querySelector('.hamburger').classList.remove("cross");
        om.style.display = "none";
        om.style.width = "0%";
        om.style.height = "0%";
      }
      else {
        document.querySelector('.hamburger').classList.add("cross");
        om.style.width = "100%";
        om.style.height = "100vh";
        om.style.display = "block";
      }
    });
  </script>
</body>
</html>
